services:
  - type: web
    name: rootv1-bot
    env: python
    buildCommand: apt-get update && apt-get install -y ffmpeg && pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DATA_DIR
        value: /data/
      - key: DISCORD_TOKEN
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
    disk:
      name: bot-data
      mountPath: /data
      sizeGB: 1
